"use client";

import { useEffect, useRef, useState } from "react";
import { IconSparkles } from "@/components/site/showcase/ShowcaseIcons";

/**
 * BoardShowcase mirrors OneCamp's collaborative whiteboard, spotlighting the
 * AI brainstorm: a prompt is typed into the "Ask AI" composer, the AI thinks,
 * then a mind map draws itself onto the infinite canvas, node by node, with the
 * edges connecting as they appear. A human collaborator's cursor is present so
 * it reads as AI-assisted, not autonomous. Reduced-motion aware; loops.
 */

const PROMPT = "Brainstorm our 2026 go-to-market plan as a mind map";

type Node = { id: string; label: string; x: number; y: number; root?: boolean };

// Percent coordinates inside the canvas area (SVG edges use a 0-100 viewBox so
// lines and labels line up regardless of the canvas size).
const NODES: Node[] = [
  { id: "root", label: "2026 GTM", x: 50, y: 50, root: true },
  { id: "plg", label: "Product-led growth", x: 24, y: 21 },
  { id: "content", label: "Content engine", x: 77, y: 20 },
  { id: "partner", label: "Partnerships", x: 15, y: 64 },
  { id: "community", label: "Community", x: 85, y: 62 },
  { id: "events", label: "Events & webinars", x: 52, y: 85 },
];

const ROOT = NODES[0];

type Phase = "typing" | "thinking" | "building" | "done";

export function BoardShowcase({ embedded = false }: { embedded?: boolean }) {
  const [typed, setTyped] = useState("");
  const [phase, setPhase] = useState<Phase>("typing");
  const [revealed, setRevealed] = useState(0); // number of nodes shown
  const reduce = useRef(false);

  useEffect(() => {
    reduce.current =
      typeof window !== "undefined" && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduce.current) {
      setTyped(PROMPT);
      setPhase("done");
      setRevealed(NODES.length);
      return;
    }

    const timers: ReturnType<typeof setTimeout>[] = [];
    let typeTimer: ReturnType<typeof setInterval>;
    let buildTimer: ReturnType<typeof setInterval>;

    const start = () => {
      setTyped("");
      setRevealed(0);
      setPhase("typing");

      let i = 0;
      typeTimer = setInterval(() => {
        i += 1;
        setTyped(PROMPT.slice(0, i));
        if (i >= PROMPT.length) {
          clearInterval(typeTimer);
          timers.push(
            setTimeout(() => {
              setPhase("thinking");
              timers.push(
                setTimeout(() => {
                  setPhase("building");
                  let n = 0;
                  buildTimer = setInterval(() => {
                    n += 1;
                    setRevealed(n);
                    if (n >= NODES.length) {
                      clearInterval(buildTimer);
                      setPhase("done");
                      timers.push(setTimeout(start, 3200)); // hold, then loop
                    }
                  }, 360);
                }, 1000),
              );
            }, 450),
          );
        }
      }, 34);
    };
    start();

    return () => {
      clearInterval(typeTimer);
      clearInterval(buildTimer);
      timers.forEach(clearTimeout);
    };
  }, []);

  const building = phase === "building" || phase === "done";

  return (
    <div className={`flex flex-col ${embedded ? "h-full min-h-0" : "h-[420px]"}`}>
      {/* Board header */}
      <header className="flex items-center justify-between border-b border-border px-4 py-3">
        <span className="text-sm font-medium text-foreground">Strategy board</span>
        <div className="flex items-center gap-2.5">
          <span
            className={`hidden items-center gap-1 rounded-full px-2 py-1 text-[10px] font-semibold transition-colors sm:inline-flex ${
              phase === "done"
                ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                : "bg-violet-500/10 text-violet-700 dark:text-violet-300"
            }`}
          >
            {phase === "done" ? (
              <>✓ Generated by AI</>
            ) : (
              <>
                <IconSparkles className="h-3 w-3" />
                {phase === "building" ? "Drawing…" : phase === "thinking" ? "Thinking…" : "AI ready"}
              </>
            )}
          </span>
          <div className="flex -space-x-2">
            <span className="grid h-6 w-6 place-items-center rounded-full bg-[#38bdf8] text-[9px] font-bold text-white ring-2 ring-background">
              DC
            </span>
            <span className="grid h-6 w-6 place-items-center rounded-full bg-[#a78bfa] text-[9px] font-bold text-white ring-2 ring-background">
              AK
            </span>
          </div>
        </div>
      </header>

      {/* Infinite-canvas area */}
      <div
        className="relative flex-1 overflow-hidden"
        style={{
          backgroundImage: "radial-gradient(currentColor 1px, transparent 1px)",
          backgroundSize: "22px 22px",
          color: "rgb(148 163 184 / 0.18)",
        }}
      >
        {/* Edges */}
        <svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden>
          {NODES.slice(1).map((n, i) => (
            <line
              key={n.id}
              x1={ROOT.x}
              y1={ROOT.y}
              x2={n.x}
              y2={n.y}
              stroke="rgb(124 108 255 / 0.45)"
              strokeWidth={0.4}
              vectorEffect="non-scaling-stroke"
              style={{
                opacity: revealed > i + 1 ? 1 : 0,
                transition: "opacity 400ms ease-out",
              }}
            />
          ))}
        </svg>

        {/* Nodes */}
        {NODES.map((n, i) => {
          const shown = i < revealed;
          return (
            <div
              key={n.id}
              className="absolute -translate-x-1/2 -translate-y-1/2"
              style={{
                left: `${n.x}%`,
                top: `${n.y}%`,
                opacity: shown ? 1 : 0,
                transform: `translate(-50%, -50%) scale(${shown ? 1 : 0.8})`,
                transition: "opacity 360ms ease-out, transform 360ms cubic-bezier(0.22,1,0.36,1)",
              }}
            >
              <div className="relative">
                <span
                  className={`block whitespace-nowrap rounded-lg border px-3 py-1.5 text-center text-[11px] font-medium shadow-sm sm:text-xs ${
                    n.root
                      ? "border-violet-400/40 bg-violet-500/15 text-violet-700 dark:text-violet-200"
                      : "border-border bg-card text-foreground"
                  }`}
                >
                  {n.label}
                </span>
                {/* AI cursor rides the most recently drawn node while building */}
                {phase === "building" && i === revealed - 1 && (
                  <span className="absolute -right-3 -top-2 inline-flex items-center gap-0.5 rounded px-1 py-0.5 text-[8px] font-semibold text-white" style={{ backgroundColor: "#7c6cff" }}>
                    <IconSparkles className="h-2.5 w-2.5" /> AI
                  </span>
                )}
              </div>
            </div>
          );
        })}

        {phase === "done" && (
          <span className="absolute left-1/2 top-3 -translate-x-1/2 animate-fade-up rounded-md border border-emerald-500/30 bg-emerald-500/[0.06] px-2 py-1 text-[10px] font-medium text-emerald-700 dark:text-emerald-300">
            ✓ 6 shapes added · edit together in real time
          </span>
        )}
      </div>

      {/* "Ask AI" composer (mirrors the real board composer) */}
      <div className="border-t border-border p-3">
        <div className="flex items-center gap-2 rounded-xl border border-border bg-background px-3 py-2">
          <IconSparkles className="h-4 w-4 flex-shrink-0 text-violet-500" />
          <span className="min-w-0 flex-1 truncate text-xs text-foreground sm:text-sm">
            {typed}
            {(phase === "typing" || phase === "thinking") && (
              <span className="ml-0.5 inline-block h-3.5 w-0.5 translate-y-0.5 animate-pulse bg-violet-500 align-middle" />
            )}
            {typed === "" && phase === "typing" && (
              <span className="text-muted-foreground">Describe what you want to draw…</span>
            )}
          </span>
          <span
            className={`flex-shrink-0 rounded-md px-2.5 py-1 text-[11px] font-medium ${
              building ? "bg-brand/80 text-white" : "bg-brand text-white"
            }`}
          >
            {phase === "building" ? "Generating…" : "Generate"}
          </span>
        </div>
      </div>
    </div>
  );
}

export default BoardShowcase;
